### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by yhyu13** [mingkai-zheng/GENIUS#1]
I was just reading another Ai build AI kinda of work : https://arxiv.org/abs/2305.02499

Where it describe GPT4 orchestrating a ML training process by picking models cards and dataset cards, the monitoring the training process and adjust hyperparameters accordingly.

Your work, however, dives into letting GPT4 design a model architectures that surpass previous SOTA arch made by human researchers

I can see a workflow for AI-build-AI here, where we specify an end goal, and letting AI build the training pipeline, and design a best-fit model.  And now we have AI designed training pipeline and AI designed SOTA model. 

But I don't see so far, any work on generating a synthetic dataset that arguments to an end goal. For instance, If I want a elder-caring robots, I need dataset on robotic arms doing housework in an elder-living environment, I also need some conversations dataset between agent and elders. I am not a AI researcher, it is just my speculation on an full AI-driven task solving pipeline, like the fully automated high quality synthetic dataset is the last piece of the puzzle.

**Comment by mingkai-zheng** [comment]
Thank you for sharing your thoughts. The idea of generating synthetic datasets is indeed an exciting area of research. Recent works, such as [StableRep: Synthetic Images from Text-to-Image Models Make Strong Visual Representation Learners](https://arxiv.org/abs/2306.00984), have shown promising results in improving the quality of visual representations using synthetic image data. While this is an exciting development, it's important to note that these approaches primarily focus on pre-training rather than directly addressing downstream tasks.

In my opinion, one of the main challenges in generating downstream datasets directly lies in the domain gaps that exist between different datasets. For instance, even in the case of a simple classification task, there are various challenges to consider, such as fine-grained classifications (e.g. face verification) vs. general classifications (ImageNet). Different datasets possess unique characteristics, and directly generating data for these diverse scenarios heavily relies on the capabilities of the generation model. Addressing these challenges requires a comprehensive approach, as it encompasses a broad and complex research area.

Developing an AI for AI pipeline is a goal that we are actively pursuing. Your idea is valuable, and we appreciate your input. We will thoroughly consider your suggestion and explore the possibility to integrate it into the framework.
